apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: {{ .Values.backend.ports.http | default 5000 }}
  selector:
    app: backend
