apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer  # Add this line
  ports:
    - port: 5173
      targetPort: {{ .Values.frontend.ports.http | default 5173 }}
      protocol: TCP   # Add protocol specification
  selector:
    app: frontend